import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full p-2 bg-black fixed inset-0 h-14 flex justify-between items-center">
          <h1 className="w-1/2 mx-auto text-lg text-center text-white">
            CRUD with JSONPLACEHOLDER API
          </h1>
          <Link href={"/"} className="w-1/2">
            <p className="w-fit mx-auto text-sm text-center text-white hover:text-white/90 hover:bg-indigo-500/90 bg-indigo-500 p-2 rounded-md hover:scale-105 transition-all duration-200 hover:transition-all hover:duration-200">
              Go to Home
            </p>
          </Link>
        </div>
        {children}
        <div className="w-full p-2 bg-black fixed h-10 bottom-0">
          <h1 className="w-1/2 mx-auto text-lg text-center text-white font-bold">
            Footer
          </h1>
        </div>
      </body>
    </html>
  );
}
